sudo: required
services:
  - docker

before_script:
  - sudo docker-compose -f docker-compose-dev.yml up -d
script:
  - docker-compose exec web bundle exec rails db:test:prepare
  - docker-compose exec web bundle exec rspec spec
after_success:
  - docker-compose down
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && sudo docker build -f Dockerfile -t mmkarim/sample_docker_web .
  - echo "$DOCKER_PASS" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push mmkarim/sample_docker_web
