sudo: required
services:
  - docker

before_install:
  - docker-compose up -d
script:
  - docker-compose exec web bundle exec rails db:test:prepare
  - docker-compose exec web bundle exec rspec spec
after_success:
  - echo "$DOCKER_PASS" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push mmkarim/sample_docker_web
