sudo: required
services:
  - docker

before_script:
  - sudo docker-compose -f docker-compose-dev.yml up -d
script:
  - docker-compose exec web bundle exec rails db:test:prepare
  - docker-compose exec web bundle exec rspec spec
after_success:
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && sudo docker build -f Dockerfile -t mmkarim/sample_docker_web .
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && sudo docker build -f Dockerfile.nginx -t mmkarim/sample_docker_nginx .
  - echo "$DOCKER_PASS" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push mmkarim/sample_docker_web
  - docker push mmkarim/sample_docker_nginx

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "sample-docker"
  env: "SampleDocker-env"
  bucket_name: "elasticbeanstalk-eu-central-1-676828608199"
  bucket_path: "sample-docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET
