version: '3'

services:
  db:
    image: postgres:9.5
    volumes:
      - ./tmp/new_db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: new
      POSTGRES_PASSWORD: new_password
  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "4000:80"
    depends_on:
      - web
  web:
    stdin_open: true
    image: mmkarim/sample_docker_web
    build: .
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
    links:
      - db
    environment:
      PG_USER: new
      PG_PORT: 5432
      PG_PASSWORD: new_password
      PG_HOST: db
      SECRET_KEY_BASE: production_test_key
      RAILS_LOG_TO_STDOUT: available
