version: '3'

services:
  nginx:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
    depends_on:
      - web
  web:
    stdin_open: true
    image: mmkarim/sample_docker_web
    build: .
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
      - "5432:5432"
    environment:
      PG_USER: clark
      PG_PORT: 5432
      PG_PASSWORD: clark
      PG_HOST: docker.for.mac.host.internal
      SECRET_KEY_BASE: production_test_key
      RAILS_LOG_TO_STDOUT: available
      RAILS_ENV: production
