apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
        - name: web
          image: mmkarim/sample_docker_web
          ports:
            - containerPort: 3000
          env:
            - name: RAILS_ENV
              value: production
            - name: PG_USER
              value: clark
            - name: PG_PASSWORD
              value: clark
            - name: PG_PORT
              value: "5432"
            - name: PG_HOST
              value: postgres-ip-service
            - name: RAILS_LOG_TO_STDOUT
              value: available
            - name: SECRET_KEY_BASE
              value: production_test_key
